
image:
  file: .gitpod.Dockerfile
ports:
  - port: 5000
    onOpen: open-browser
    visibility: private
tasks:
  - init: pipenv sync
    command: pipenv run mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /workspace/tuto-mlflow/artifacts --host 0.0.0.0

vscode:
  extensions:
    - ms-python.python