
image:
  file: .gitpod.Dockerfile
ports:
  - port: 5000
    onOpen: open-browser
    visibility: private
tasks:
  - init: python -m venv .venv
    command: |
      source .venv/bin/activate
      pip install pip-tools

vscode:
  extensions:
    - ms-python.python